/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TalentApplicationRouteImport } from './routes/talent-application'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiPublicSupportChatRouteImport } from './routes/api/public/support-chat'
import { Route as AuthenticatedPortalTalentRouteImport } from './routes/_authenticated/portal/talent'
import { Route as AuthenticatedPortalStudentRouteImport } from './routes/_authenticated/portal/student'
import { Route as AuthenticatedPortalPmRouteImport } from './routes/_authenticated/portal/pm'
import { Route as AuthenticatedPortalClientRouteImport } from './routes/_authenticated/portal/client'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentApplicationRoute = TalentApplicationRouteImport.update({
  id: '/talent-application',
  path: '/talent-application',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportChatRoute = ApiPublicSupportChatRouteImport.update({
  id: '/api/public/support-chat',
  path: '/api/public/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalTalentRoute =
  AuthenticatedPortalTalentRouteImport.update({
    id: '/portal/talent',
    path: '/portal/talent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStudentRoute =
  AuthenticatedPortalStudentRouteImport.update({
    id: '/portal/student',
    path: '/portal/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPmRoute = AuthenticatedPortalPmRouteImport.update({
  id: '/portal/pm',
  path: '/portal/pm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalClientRoute =
  AuthenticatedPortalClientRouteImport.update({
    id: '/portal/client',
    path: '/portal/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/portal/admin',
    path: '/portal/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/pm': typeof AuthenticatedPortalPmRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/pm': typeof AuthenticatedPortalPmRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/portal/client': typeof AuthenticatedPortalClientRoute
  '/_authenticated/portal/pm': typeof AuthenticatedPortalPmRoute
  '/_authenticated/portal/student': typeof AuthenticatedPortalStudentRoute
  '/_authenticated/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/agency'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/invite/$token'
    | '/portal/admin'
    | '/portal/client'
    | '/portal/pm'
    | '/portal/student'
    | '/portal/talent'
    | '/api/public/support-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/agency'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/invite/$token'
    | '/portal/admin'
    | '/portal/client'
    | '/portal/pm'
    | '/portal/student'
    | '/portal/talent'
    | '/api/public/support-chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/agency'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/invite/$token'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/client'
    | '/_authenticated/portal/pm'
    | '/_authenticated/portal/student'
    | '/_authenticated/portal/talent'
    | '/api/public/support-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AgencyRoute: typeof AgencyRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TalentApplicationRoute: typeof TalentApplicationRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicSupportChatRoute: typeof ApiPublicSupportChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-application': {
      id: '/talent-application'
      path: '/talent-application'
      fullPath: '/talent-application'
      preLoaderRoute: typeof TalentApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support-chat': {
      id: '/api/public/support-chat'
      path: '/api/public/support-chat'
      fullPath: '/api/public/support-chat'
      preLoaderRoute: typeof ApiPublicSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/talent': {
      id: '/_authenticated/portal/talent'
      path: '/portal/talent'
      fullPath: '/portal/talent'
      preLoaderRoute: typeof AuthenticatedPortalTalentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/student': {
      id: '/_authenticated/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AuthenticatedPortalStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/pm': {
      id: '/_authenticated/portal/pm'
      path: '/portal/pm'
      fullPath: '/portal/pm'
      preLoaderRoute: typeof AuthenticatedPortalPmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/client': {
      id: '/_authenticated/portal/client'
      path: '/portal/client'
      fullPath: '/portal/client'
      preLoaderRoute: typeof AuthenticatedPortalClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedPortalClientRoute: typeof AuthenticatedPortalClientRoute
  AuthenticatedPortalPmRoute: typeof AuthenticatedPortalPmRoute
  AuthenticatedPortalStudentRoute: typeof AuthenticatedPortalStudentRoute
  AuthenticatedPortalTalentRoute: typeof AuthenticatedPortalTalentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedPortalClientRoute: AuthenticatedPortalClientRoute,
  AuthenticatedPortalPmRoute: AuthenticatedPortalPmRoute,
  AuthenticatedPortalStudentRoute: AuthenticatedPortalStudentRoute,
  AuthenticatedPortalTalentRoute: AuthenticatedPortalTalentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AgencyRoute: AgencyRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TalentApplicationRoute: TalentApplicationRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicSupportChatRoute: ApiPublicSupportChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
