/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TalentApplicationRouteImport } from './routes/talent-application'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as ApiPublicSupportChatRouteImport } from './routes/api/public/support-chat'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AuthenticatedWorkspaceIdRouteImport } from './routes/_authenticated/workspace.$id'
import { Route as AuthenticatedProjectSlugRouteImport } from './routes/_authenticated/project.$slug'
import { Route as AuthenticatedPortalTalentRouteImport } from './routes/_authenticated/portal/talent'
import { Route as AuthenticatedPortalStudentRouteImport } from './routes/_authenticated/portal/student'
import { Route as AuthenticatedPortalPmRouteImport } from './routes/_authenticated/portal/pm'
import { Route as AuthenticatedPortalClientRouteImport } from './routes/_authenticated/portal/client'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal/admin'
import { Route as AuthenticatedLearningSlugRouteImport } from './routes/_authenticated/learning.$slug'
import { Route as AuthenticatedExamSlugRouteImport } from './routes/_authenticated/exam.$slug'
import { Route as AuthenticatedEnrolCallbackRouteImport } from './routes/_authenticated/enrol.callback'
import { Route as AuthenticatedCertificateIdRouteImport } from './routes/_authenticated/certificate.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentApplicationRoute = TalentApplicationRouteImport.update({
  id: '/talent-application',
  path: '/talent-application',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const ApiPublicSupportChatRoute = ApiPublicSupportChatRouteImport.update({
  id: '/api/public/support-chat',
  path: '/api/public/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedWorkspaceIdRoute =
  AuthenticatedWorkspaceIdRouteImport.update({
    id: '/workspace/$id',
    path: '/workspace/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectSlugRoute =
  AuthenticatedProjectSlugRouteImport.update({
    id: '/project/$slug',
    path: '/project/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalTalentRoute =
  AuthenticatedPortalTalentRouteImport.update({
    id: '/portal/talent',
    path: '/portal/talent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStudentRoute =
  AuthenticatedPortalStudentRouteImport.update({
    id: '/portal/student',
    path: '/portal/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPmRoute = AuthenticatedPortalPmRouteImport.update({
  id: '/portal/pm',
  path: '/portal/pm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalClientRoute =
  AuthenticatedPortalClientRouteImport.update({
    id: '/portal/client',
    path: '/portal/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/portal/admin',
    path: '/portal/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningSlugRoute =
  AuthenticatedLearningSlugRouteImport.update({
    id: '/learning/$slug',
    path: '/learning/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamSlugRoute = AuthenticatedExamSlugRouteImport.update({
  id: '/exam/$slug',
  path: '/exam/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnrolCallbackRoute =
  AuthenticatedEnrolCallbackRouteImport.update({
    id: '/enrol/callback',
    path: '/enrol/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificateIdRoute =
  AuthenticatedCertificateIdRouteImport.update({
    id: '/certificate/$id',
    path: '/certificate/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/agency': typeof AgencyRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/academy/': typeof AcademyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/certificate/$id': typeof AuthenticatedCertificateIdRoute
  '/enrol/callback': typeof AuthenticatedEnrolCallbackRoute
  '/exam/$slug': typeof AuthenticatedExamSlugRoute
  '/learning/$slug': typeof AuthenticatedLearningSlugRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/pm': typeof AuthenticatedPortalPmRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/project/$slug': typeof AuthenticatedProjectSlugRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agency': typeof AgencyRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/academy': typeof AcademyIndexRoute
  '/blog': typeof BlogIndexRoute
  '/certificate/$id': typeof AuthenticatedCertificateIdRoute
  '/enrol/callback': typeof AuthenticatedEnrolCallbackRoute
  '/exam/$slug': typeof AuthenticatedExamSlugRoute
  '/learning/$slug': typeof AuthenticatedLearningSlugRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/pm': typeof AuthenticatedPortalPmRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/project/$slug': typeof AuthenticatedProjectSlugRoute
  '/workspace/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/agency': typeof AgencyRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/talent-application': typeof TalentApplicationRoute
  '/terms': typeof TermsRoute
  '/work': typeof WorkRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/academy/': typeof AcademyIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/certificate/$id': typeof AuthenticatedCertificateIdRoute
  '/_authenticated/enrol/callback': typeof AuthenticatedEnrolCallbackRoute
  '/_authenticated/exam/$slug': typeof AuthenticatedExamSlugRoute
  '/_authenticated/learning/$slug': typeof AuthenticatedLearningSlugRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/portal/client': typeof AuthenticatedPortalClientRoute
  '/_authenticated/portal/pm': typeof AuthenticatedPortalPmRoute
  '/_authenticated/portal/student': typeof AuthenticatedPortalStudentRoute
  '/_authenticated/portal/talent': typeof AuthenticatedPortalTalentRoute
  '/_authenticated/project/$slug': typeof AuthenticatedProjectSlugRoute
  '/_authenticated/workspace/$id': typeof AuthenticatedWorkspaceIdRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/support-chat': typeof ApiPublicSupportChatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/agency'
    | '/blog'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/work'
    | '/academy/$slug'
    | '/blog/$slug'
    | '/invite/$token'
    | '/academy/'
    | '/blog/'
    | '/certificate/$id'
    | '/enrol/callback'
    | '/exam/$slug'
    | '/learning/$slug'
    | '/portal/admin'
    | '/portal/client'
    | '/portal/pm'
    | '/portal/student'
    | '/portal/talent'
    | '/project/$slug'
    | '/workspace/$id'
    | '/api/public/paystack-webhook'
    | '/api/public/support-chat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agency'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/work'
    | '/academy/$slug'
    | '/blog/$slug'
    | '/invite/$token'
    | '/academy'
    | '/blog'
    | '/certificate/$id'
    | '/enrol/callback'
    | '/exam/$slug'
    | '/learning/$slug'
    | '/portal/admin'
    | '/portal/client'
    | '/portal/pm'
    | '/portal/student'
    | '/portal/talent'
    | '/project/$slug'
    | '/workspace/$id'
    | '/api/public/paystack-webhook'
    | '/api/public/support-chat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/agency'
    | '/blog'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/talent-application'
    | '/terms'
    | '/work'
    | '/academy/$slug'
    | '/blog/$slug'
    | '/invite/$token'
    | '/academy/'
    | '/blog/'
    | '/_authenticated/certificate/$id'
    | '/_authenticated/enrol/callback'
    | '/_authenticated/exam/$slug'
    | '/_authenticated/learning/$slug'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/client'
    | '/_authenticated/portal/pm'
    | '/_authenticated/portal/student'
    | '/_authenticated/portal/talent'
    | '/_authenticated/project/$slug'
    | '/_authenticated/workspace/$id'
    | '/api/public/paystack-webhook'
    | '/api/public/support-chat'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AgencyRoute: typeof AgencyRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TalentApplicationRoute: typeof TalentApplicationRoute
  TermsRoute: typeof TermsRoute
  WorkRoute: typeof WorkRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicSupportChatRoute: typeof ApiPublicSupportChatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-application': {
      id: '/talent-application'
      path: '/talent-application'
      fullPath: '/talent-application'
      preLoaderRoute: typeof TalentApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/api/public/support-chat': {
      id: '/api/public/support-chat'
      path: '/api/public/support-chat'
      fullPath: '/api/public/support-chat'
      preLoaderRoute: typeof ApiPublicSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/$id': {
      id: '/_authenticated/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project/$slug': {
      id: '/_authenticated/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof AuthenticatedProjectSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/talent': {
      id: '/_authenticated/portal/talent'
      path: '/portal/talent'
      fullPath: '/portal/talent'
      preLoaderRoute: typeof AuthenticatedPortalTalentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/student': {
      id: '/_authenticated/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AuthenticatedPortalStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/pm': {
      id: '/_authenticated/portal/pm'
      path: '/portal/pm'
      fullPath: '/portal/pm'
      preLoaderRoute: typeof AuthenticatedPortalPmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/client': {
      id: '/_authenticated/portal/client'
      path: '/portal/client'
      fullPath: '/portal/client'
      preLoaderRoute: typeof AuthenticatedPortalClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning/$slug': {
      id: '/_authenticated/learning/$slug'
      path: '/learning/$slug'
      fullPath: '/learning/$slug'
      preLoaderRoute: typeof AuthenticatedLearningSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$slug': {
      id: '/_authenticated/exam/$slug'
      path: '/exam/$slug'
      fullPath: '/exam/$slug'
      preLoaderRoute: typeof AuthenticatedExamSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enrol/callback': {
      id: '/_authenticated/enrol/callback'
      path: '/enrol/callback'
      fullPath: '/enrol/callback'
      preLoaderRoute: typeof AuthenticatedEnrolCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate/$id': {
      id: '/_authenticated/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof AuthenticatedCertificateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCertificateIdRoute: typeof AuthenticatedCertificateIdRoute
  AuthenticatedEnrolCallbackRoute: typeof AuthenticatedEnrolCallbackRoute
  AuthenticatedExamSlugRoute: typeof AuthenticatedExamSlugRoute
  AuthenticatedLearningSlugRoute: typeof AuthenticatedLearningSlugRoute
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedPortalClientRoute: typeof AuthenticatedPortalClientRoute
  AuthenticatedPortalPmRoute: typeof AuthenticatedPortalPmRoute
  AuthenticatedPortalStudentRoute: typeof AuthenticatedPortalStudentRoute
  AuthenticatedPortalTalentRoute: typeof AuthenticatedPortalTalentRoute
  AuthenticatedProjectSlugRoute: typeof AuthenticatedProjectSlugRoute
  AuthenticatedWorkspaceIdRoute: typeof AuthenticatedWorkspaceIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCertificateIdRoute: AuthenticatedCertificateIdRoute,
  AuthenticatedEnrolCallbackRoute: AuthenticatedEnrolCallbackRoute,
  AuthenticatedExamSlugRoute: AuthenticatedExamSlugRoute,
  AuthenticatedLearningSlugRoute: AuthenticatedLearningSlugRoute,
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedPortalClientRoute: AuthenticatedPortalClientRoute,
  AuthenticatedPortalPmRoute: AuthenticatedPortalPmRoute,
  AuthenticatedPortalStudentRoute: AuthenticatedPortalStudentRoute,
  AuthenticatedPortalTalentRoute: AuthenticatedPortalTalentRoute,
  AuthenticatedProjectSlugRoute: AuthenticatedProjectSlugRoute,
  AuthenticatedWorkspaceIdRoute: AuthenticatedWorkspaceIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AgencyRoute: AgencyRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TalentApplicationRoute: TalentApplicationRoute,
  TermsRoute: TermsRoute,
  WorkRoute: WorkRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicSupportChatRoute: ApiPublicSupportChatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
