/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalStudentRouteImport } from './routes/_authenticated/portal.student'
import { Route as AuthenticatedPortalClientRouteImport } from './routes/_authenticated/portal.client'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalStudentRoute =
  AuthenticatedPortalStudentRouteImport.update({
    id: '/portal/student',
    path: '/portal/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalClientRoute =
  AuthenticatedPortalClientRouteImport.update({
    id: '/portal/client',
    path: '/portal/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/portal/client': typeof AuthenticatedPortalClientRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy': typeof AcademyRoute
  '/agency': typeof AgencyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/portal/client': typeof AuthenticatedPortalClientRoute
  '/_authenticated/portal/student': typeof AuthenticatedPortalStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/agency'
    | '/login'
    | '/signup'
    | '/portal/client'
    | '/portal/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/agency'
    | '/login'
    | '/signup'
    | '/portal/client'
    | '/portal/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy'
    | '/agency'
    | '/login'
    | '/signup'
    | '/_authenticated/portal/client'
    | '/_authenticated/portal/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademyRoute: typeof AcademyRoute
  AgencyRoute: typeof AgencyRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/student': {
      id: '/_authenticated/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AuthenticatedPortalStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/client': {
      id: '/_authenticated/portal/client'
      path: '/portal/client'
      fullPath: '/portal/client'
      preLoaderRoute: typeof AuthenticatedPortalClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalClientRoute: typeof AuthenticatedPortalClientRoute
  AuthenticatedPortalStudentRoute: typeof AuthenticatedPortalStudentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalClientRoute: AuthenticatedPortalClientRoute,
  AuthenticatedPortalStudentRoute: AuthenticatedPortalStudentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademyRoute: AcademyRoute,
  AgencyRoute: AgencyRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
