-- Stage 5 Academy flow: student-owned progress, Exams, projects, and certificates.
CREATE TABLE IF NOT EXISTS public.lesson_progress (student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, lesson_id uuid NOT NULL REFERENCES public.lessons(id) ON DELETE CASCADE, completed_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(student_id, lesson_id));
CREATE TABLE IF NOT EXISTS public.exam_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE, questions jsonb NOT NULL DEFAULT '[]'::jsonb, answers jsonb NOT NULL DEFAULT '{}'::jsonb, score numeric, passed boolean, started_at timestamptz NOT NULL DEFAULT now(), submitted_at timestamptz, UNIQUE(id));
CREATE TABLE IF NOT EXISTS public.student_projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE, brief text NOT NULL, submission_url text, submission_text text, submission_file_path text, ai_verdict text, ai_feedback text, status text NOT NULL DEFAULT 'submitted' CHECK(status IN ('submitted','approved','rejected')), reviewer_note text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE ON public.lesson_progress,public.exam_attempts,public.student_projects TO authenticated; GRANT ALL ON public.lesson_progress,public.exam_attempts,public.student_projects TO service_role;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY; ALTER TABLE public.exam_attempts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.student_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "students own lesson progress" ON public.lesson_progress FOR ALL TO authenticated USING(student_id=auth.uid()) WITH CHECK(student_id=auth.uid() AND EXISTS(SELECT 1 FROM public.enrollments e JOIN public.lessons l ON l.course_id=e.course_id WHERE e.student_id=auth.uid() AND l.id=lesson_id));
CREATE POLICY "students own exams" ON public.exam_attempts FOR ALL TO authenticated USING(student_id=auth.uid()) WITH CHECK(student_id=auth.uid() AND EXISTS(SELECT 1 FROM public.enrollments e WHERE e.student_id=auth.uid() AND e.course_id=course_id));
CREATE POLICY "students own projects" ON public.student_projects FOR ALL TO authenticated USING(student_id=auth.uid()) WITH CHECK(student_id=auth.uid() AND EXISTS(SELECT 1 FROM public.enrollments e WHERE e.student_id=auth.uid() AND e.course_id=course_id));
CREATE POLICY "admin reviews student projects" ON public.student_projects FOR SELECT TO authenticated USING(public.is_admin());
CREATE POLICY "admin updates student projects" ON public.student_projects FOR UPDATE TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());
